"""Initial migration.

Revision ID: 219a3bfe5c5e
Revises: e698230bca78
Create Date: 2022-05-31 02:29:27.439090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219a3bfe5c5e'
down_revision = 'e698230bca78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data_upd', sa.Column('driving_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_data_upd', 'driving_number')
    # ### end Alembic commands ###
