"""Initial migration.

Revision ID: 2c4d478455b1
Revises: a9073b5782b3
Create Date: 2022-05-30 11:14:35.552272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c4d478455b1'
down_revision = 'a9073b5782b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_rate_total_upd', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'driver_rate_total_upd', 'user_final', ['user_id'], ['id'])
    op.add_column('sensor_data_upd_2', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sensor_data_upd_2', 'user_final', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensor_data_upd_2', type_='foreignkey')
    op.drop_column('sensor_data_upd_2', 'user_id')
    op.drop_constraint(None, 'driver_rate_total_upd', type_='foreignkey')
    op.drop_column('driver_rate_total_upd', 'user_id')
    # ### end Alembic commands ###
