"""Initial migration.

Revision ID: e698230bca78
Revises: 2c4d478455b1
Create Date: 2022-05-30 11:49:46.860335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e698230bca78'
down_revision = '2c4d478455b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data_upd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AccX', sa.Float(), nullable=True),
    sa.Column('AccY', sa.Float(), nullable=True),
    sa.Column('AccZ', sa.Float(), nullable=True),
    sa.Column('GPS_Long', sa.Float(), nullable=True),
    sa.Column('GPS_Lat', sa.Float(), nullable=True),
    sa.Column('GyroX', sa.Float(), nullable=True),
    sa.Column('GyroY', sa.Float(), nullable=True),
    sa.Column('GyroZ', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_final.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sensor_data_upd_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_data_upd_2',
    sa.Column('id', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('AccX', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AccY', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('AccZ', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GPS_Long', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GPS_Lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GyroX', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GyroY', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('GyroZ', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_final.id'], name='sensor_data_upd_2_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sensor_data_upd_2_pkey')
    )
    op.drop_table('sensor_data_upd')
    # ### end Alembic commands ###
