"""Initial migration.

Revision ID: ed6a9a1a3328
Revises: 04011c4bdcd7
Create Date: 2022-06-10 07:34:09.210395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6a9a1a3328'
down_revision = '04011c4bdcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_rate_total_upd', sa.Column('gps_lat_1', sa.Float(), nullable=True))
    op.add_column('driver_rate_total_upd', sa.Column('gps_long_1', sa.Float(), nullable=True))
    op.add_column('driver_rate_total_upd', sa.Column('gps_lat_2', sa.Float(), nullable=True))
    op.add_column('driver_rate_total_upd', sa.Column('gps_long_2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_rate_total_upd', 'gps_long_2')
    op.drop_column('driver_rate_total_upd', 'gps_lat_2')
    op.drop_column('driver_rate_total_upd', 'gps_long_1')
    op.drop_column('driver_rate_total_upd', 'gps_lat_1')
    # ### end Alembic commands ###
