"""Initial migration.

Revision ID: f6aa4c3a51ed
Revises: 219a3bfe5c5e
Create Date: 2022-05-31 11:52:27.002188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6aa4c3a51ed'
down_revision = '219a3bfe5c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data_upd', sa.Column('driving_name', sa.String(length=255), nullable=True))
    op.drop_column('sensor_data_upd', 'driving_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data_upd', sa.Column('driving_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('sensor_data_upd', 'driving_name')
    # ### end Alembic commands ###
